### ISSUE TITLE
Preparing translations

### ISSUE THREAD

**Issue by alex-nitrokey** [vletoux/OpenPGP-CSP#8]
It would be great to have possibilities at hand to let people easily translate the english version to other languages.

I guess VisualStudio has such a features, but I don't know. I would add German translations as a test, if you like.

**Comment by vletoux** [comment]
I do not understand: the source already includes german translation:
https://github.com/vletoux/OpenPGP-CSP/blob/master/OpenPGPCsp/OpenPGPCsp-DE.rc

All everyone has to do is to copy this file, replace the german language reference and recompile the project.
If I remember correctly, the release available online does not include the german translation because the compilation was done after.

**Comment by alex-nitrokey** [comment]
I see, didn't know that this was included in the last commits. Thanks!
